from __future__ import annotations

import hashlib
from datetime import datetime, timezone

import pandas as pd
from sqlalchemy import insert, select
from sqlalchemy.engine import Engine

from autminietl.db import dataset_versions, records


def compute_version_hash(df: pd.DataFrame) -> str:
    stable = df.sort_values(by=["external_id", "title"]).reset_index(drop=True)
    payload = stable.to_json(date_format="iso", orient="records")
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def upsert_dataset_version(engine: Engine, df: pd.DataFrame, source: str) -> int:
    version_hash = compute_version_hash(df)
    with engine.begin() as conn:
        existing = conn.execute(
            select(dataset_versions.c.id).where(dataset_versions.c.version_hash == version_hash)
        ).scalar_one_or_none()
        if existing is not None:
            return int(existing)

        inserted = conn.execute(
            insert(dataset_versions).values(
                version_hash=version_hash,
                created_at=datetime.now(timezone.utc),
                source=source,
                row_count=len(df),
                notes="auto-generated by pipeline",
            )
        )
        return int(inserted.inserted_primary_key[0])


def load_records(engine: Engine, df: pd.DataFrame, version_id: int) -> int:
    to_insert = []
    for row in df.to_dict(orient="records"):
        to_insert.append(
            {
                "version_id": version_id,
                "external_id": str(row["external_id"]),
                "title": row["title"],
                "body": row["body"],
                "value": float(row["value"]),
                "category": row["category"],
                "collected_at": row["collected_at"],
                "source_url": row.get("source_url"),
            }
        )

    with engine.begin() as conn:
        conn.execute(insert(records), to_insert)

    return len(to_insert)
