from __future__ import annotations

import hashlib
from datetime import datetime, timezone

import pandas as pd
from sqlalchemy import insert, select
from sqlalchemy.engine import Engine

from autminietl.db import dataset_versions, records


def compute_version_hash(df: pd.DataFrame) -> str:
    hash_columns = ["external_id", "title", "body", "value", "category", "source_url"]
    stable = (
        df[hash_columns]
        .sort_values(by=["external_id", "title"])
        .reset_index(drop=True)
    )
    payload = stable.to_json(date_format="iso", orient="records")
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def upsert_dataset_version(engine: Engine, df: pd.DataFrame, source: str) -> tuple[int, bool]:
    version_hash = compute_version_hash(df)
    with engine.begin() as conn:
        existing = conn.execute(
            select(dataset_versions.c.id).where(dataset_versions.c.version_hash == version_hash)
        ).scalar_one_or_none()
        if existing is not None:
            return int(existing), False

        inserted = conn.execute(
            insert(dataset_versions).values(
                version_hash=version_hash,
                created_at=datetime.now(timezone.utc),
                source=source,
                row_count=len(df),
                notes="auto-generated by pipeline",
            )
        )
        return int(inserted.inserted_primary_key[0]), True


def has_records_for_version(engine: Engine, version_id: int) -> bool:
    with engine.begin() as conn:
        existing = conn.execute(
            select(records.c.id).where(records.c.version_id == version_id).limit(1)
        ).scalar_one_or_none()
    return existing is not None


def load_records(engine: Engine, df: pd.DataFrame, version_id: int) -> int:
    if df.empty:
        return 0

    rows = df.to_dict(orient="records")
    to_insert = [
        {
            "version_id": version_id,
            "external_id": str(row["external_id"]),
            "title": row["title"],
            "body": row["body"],
            "value": float(row["value"]),
            "category": row["category"],
            "collected_at": row["collected_at"],
            "source_url": row.get("source_url"),
        }
        for row in rows
    ]

    with engine.begin() as conn:
        conn.execute(insert(records), to_insert)

    return len(to_insert)
